config/routes.rb
Rails.application.routes.draw do

  root 'events#index'

  resources :events do
    resources :locations
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_one :location
	validates :name,  presence:true
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :event
end

app/models/static.rb
class Static < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@events = Event.all
	end
	def new
		@event = Event.new
	end
	def create
		@event = Event.new(event_params)
	     respond_to do |format|
	     	if @event.save
	     		format.html { redirect_to @event, notice: 'Event was successfully created.' }
	     	    format.json { render json: @event, :status => :created, location: @event }
	     	else
	     		format.html { render_to action: 'new' }
	     		format.json { render json: @event.errors, :status => :unprocessable_entity }
	     	end
	    end
	end
	def show
		@event = Event.find(params[:id])
	end
	def edit
		@event = Event.find(params[:id])
	end
	def update
		@event = Event.find(params[:id])
		respond_to do |format|
			if @event.update(event_params)
				format.html { redirect_to @event, notice: 'Event was successfully updated.'}
				format.json { render json: @event, :status => :created, location: @event }
			else
				format.html { render action: 'update' }
				format.json { render json: @event.errors, :status => :unprocessable_entity }
			end
		end
	end
	 def destroy
  	@event = Event.find(params[:id])
  	@event.destroy
  	 redirect_to events_path
  end
	private
	def event_params
	params.require(:event).permit(:name, :age)	
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	def index
		@event = Event.find(params[:event_id])
		@locations = @event.location
	end
	def new
		@event = Event.find(params[:event_id])
		@location = @event.build_location
	end
	def create
		@event = Event.find(params[:event_id])
		@location = @event.build_location(location_params)
		respond_to do |format| 
			if @location.save
				format.html { redirect_to ([@event, @location]), notice: 'Location was successfully created.' }
				format.json { render json: @location, :status => :created, location: @location }
			else
				format.html { render action: 'new' }
				format.json { render json: @location.errors, :status => :unprocessable_entity }
			end
		end
	end
	def show
		@event = Event.find(params[:event_id])
		@location = @event.location
    end
    def edit
    	@event = Event.find(params[:event_id])
    	@location = @event.location
    end
    def update
    	@event = Event.find(params[:event_id])
    	@location = @event.location
    	respond_to do |format|
    		if @location.update(location_params)
    			format.html { redirect_to ([@event, @location]), notice: 'Location was successfully updated.' }
    			format.json { render json: @location, :status => :updated, location: @location }
    		else
    			format.html { render action: 'update' }
    			format.json { render json: @location.errors, :status => :unprocessable_entity }
    		end
    	end
    end
    def destroy
    	@event = Event.find(params[:event_id])
    	@location = @event.location
    	@location.destroy
    	redirect_to event_locations_path
    end
	private
	def location_params
		params.require(:location).permit(:address)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |k| %>
 <% if @event.errors.any? %>
  <div id='error explanation?'>
  <h2><%= pluralize(@event.errors.count,'error')%> Prohibited event from being saved: </h2>
  <ul>
  <% @event.full_msg.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
  <% end %>
  <p>
  <%= k.label :name %>
  <%= k.text_field :name %>
  </p>

  <p>
  <%= k.label :age %>
  <%= k.text_field :age %>
  </p>

  <p>
  <%= k.submit :submit %>
  </p>
  <% end %>

app/views/events/edit.html.erb
<h1>Edit Event </h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>Listing event</h1>
<table>
	<tr>
	<th>Name</th>
	<th>Age</th>
	</tr>
<% @events.each do |event| %>
 <tr>
 <td><%= event.name %></td>
 <td><%= event.age %></td>
 <td><%= link_to 'show', event_path(event) %></td>
 <td><%= link_to 'edit', edit_event_path(event) %></td>
 <% if !event.location.nil? %>
 <% @location = event.location %>
 <td><%= link_to 'location', event_location_path(event, @location) %></td>
 <% end %>
 <td><%= link_to 'destroy', event_path(event),
          method: :delete,data: { clear: 'Are you sure?' } %></td>
   <% if !event.location.nil? %>
    	<td><% @location = event.location.address %></td>
	    <td><%= link_to 'location', event_location_path(event,@location) %></td>
	<% end %>
	<td><%= link_to 'location new', new_event_location_path(event) %></td>
</tr>
<% end %>


</table>
<%= link_to 'new event', new_event_path %>

app/views/events/new.html.erb
<h1>This is my home page</h1>
<%= render 'form' %>

app/views/events/show.html.erb
<% if flash[:notice] %>
  <div id='notice'><%= flash[:notice] %></div>
 <% end %>
<p>
<strong>Name</strong>
<%= @event.name %>
</p>
<p>
<strong>Age</strong>
<%= @event.age %>
</p>

<%= link_to 'Back', events_path(@event) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devise</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%#= notice %></p>
       <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for ([@event, @location]) do |f| %>
  <% if @location.errors.any? %>
	<div id='error explanation' >
		<h2><%= pluralize(@location.errors.count,'error')%> Prohibited location from being saved:</h2>
		<ul>
			<% @location.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
  <% end %>
	<p>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</p>
	<p>
		<%= f.submit :submit %>
	</p>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit Location </h1>
<%= render 'form' %>

app/views/locations/index.html.erb
<h1>Listing Location</h1>
<table>
	<tr>
		<th>Address</th>
	</tr>
	<tr>
		<td><%= @locations.address %></td>
		<td><%= link_to 'show', event_location_path(@event, @locations) %></td>
		<td><%= link_to 'edit', edit_event_location_path(@event, @locations) %></td>
		<td><%= link_to 'events', event_path(@event) %></td>
		<td><%= link_to 'destroy', event_location_path(@event, @locations),
			method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>
	
</table>

app/views/locations/new.html.erb
<h1>New Location</h1>
<%= render 'form' %>

app/views/locations/show.html.erb
<p>
<strong>Address</strong>
<%= @location.address %>
</p>
<%= link_to 'Back', event_locations_path %>
<%= link_to 'Edit', edit_event_location_path %>